### ISSUE TITLE
Renaming Github organization to spaam-community

### ISSUE THREAD

**Issue by maxibor** [SPAAM-community/spaam-community.github.io#4]
Now that SPAAM is more than "just" a workshop, it would be nice to rename this Github organization (and hence the address of the website) to something more fitting to what SPAAM is.
**SPAAM-community** could be a good fit.

**Comment by jfy133** [comment]
IIRC it was already taken :(

**Comment by jfy133** [comment]
Oh no you're right!

**Comment by jfy133** [comment]
I suggest we do this after SPAAM2

**Comment by jfy133** [comment]
On there otherhand it would break the AncientMetagenomeDir preprint... I dunno if github would do forwarding?

**Comment by maxibor** [comment]
Yes https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username

**Comment by maxibor** [comment]
That's why I suggest to do it now, so that you can update the links in the preprint

**Comment by jfy133** [comment]
https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization

**Comment by jfy133** [comment]
"After changing your organization's name, your old organization name becomes available for someone else to claim. "?

**Comment by jfy133** [comment]
OK, Maxime also found some other redirect hacks! Will do this in next hour or so.
